# Generated by Django 6.0.3 on 2026-03-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AlterField(
            model_name='login',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(null=True),
        ),
    ]
