# Generated by Django 6.0.5 on 2026-06-22 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A short bio about yourself.', max_length=500)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('avatar', models.ImageField(blank=True, default='avatars/default_avatar.png', upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this profile was last updated.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
