# Generated by Django 6.0.5 on 2026-06-18 07:30

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel & Adventure'), ('finance', 'Business & Finance'), ('education', 'Education & Tutorials')], default='tech', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('blog_title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(default='', upload_to='blog_images')),
                ('blog_content', django_ckeditor_5.fields.CKEditor5Field(max_length=10000)),
                ('blog_summary', models.TextField(max_length=255)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('share', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
